[package]
name = "cskburn-cli"
version = "2.0.0-alpha.1"
description = "CLI tool for programming LISTENAI CSK series chips"

edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "cskburn"
path = "src/main.rs"

[dependencies]
cskburn = { workspace = true }
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
console = "0.16.0"
dialoguer = "0.11.0"
env_logger = "0.11.8"
indicatif = "0.18.0"
log = { workspace = true }
md5 = "0.8.0"
